name: build
in: query
description: |
  Optional build of the target Actor.

  It can be either a build tag or build number. By default, the run uses
  the build specified in the default run configuration for the target
  Actor (typically `latest`).
style: form
explode: true
schema:
  type: string
  example: beta
