get:
  tags:
    - Actors/Actor builds
  summary: Get OpenAPI definition
  description: |
    Get the OpenAPI definition for Actor builds. Two similar endpoints are available:

    - [First endpoint](/api/v2/act-openapi-json-get): Requires both `actorId` and `buildId`. Use `default` as the `buildId` to get the OpenAPI schema for the default Actor build.

    - [Second endpoint](/api/v2/actor-build-openapi-json-get): Requires only `buildId`.

    Get the OpenAPI definition for a specific Actor build.

    To fetch the default Actor build, simply pass `default` as the `buildId`.
    Authentication is based on the build's unique ID. No authentication token is required.

    :::note

    You can also use the [`/api/v2/actor-build-openapi-json-get`](/api/v2/actor-build-openapi-json-get) endpoint to get the OpenAPI definition for a build.

    :::
  operationId: act_openapi_json_get
  security: []
  parameters:
    - $ref: "../../components/parameters/runAndBuildParameters.yaml#/actorId"
    - $ref: "../../components/parameters/runAndBuildParameters.yaml#/buildIdWithDefault"
  responses:
    "200":
      description: The OpenAPI specification document for the Actor build.
      headers: {}
      content:
        application/json:
          schema:
            type: object
            description: A standard OpenAPI 3.x JSON document.
    "400":
      $ref: ../../components/responses/BadRequest.yaml
    "404":
      description: Not found - the requested resource was not found.
      content:
        application/json:
          schema:
            anyOf:
              - $ref: "../../components/schemas/common/errors/ActorErrors.yaml#/ActorNotFoundError"
              - $ref: "../../components/schemas/common/errors/ActorErrors.yaml#/ActorBuildNotFoundError"
    "405":
      $ref: ../../components/responses/MethodNotAllowed.yaml
    "429":
      $ref: ../../components/responses/TooManyRequests.yaml
