extends:
    - recommended

rules:
    no-unused-components: error

theme:
    openapi:
        requiredPropsFirst: true
        noAutoAuth: true
        hideDownloadButton: true
        onlyRequiredInSamples: true
        nativeScrollbars: true
        scrollYOffset: 68
        theme:
            colors:
                primary:
                    main: '#1f9ec8'
