# See https://redoc.ly/docs/cli/configuration/ for more information.
apis:
    main@v1:
        root: openapi/openapi/openapi.yaml

extends:
    - recommended

rules:
    spec: error
    no-unused-components: error

theme:
    htmlTemplate: openapi/docs/index.html

    openapi:
        expandDefaultResponse: true
        expandDefaultRequest: true
        expandResponses: all
        schemasExpansionLevel: 2
        jsonSamplesExpandLevel: 2

plugins:
    - openapi/plugins/apify.js

decorators:
    apify/legacy-doc-url-decorator: on
    apify/client-references-links-decorator: on
