extends:
    - recommended

rules:
    no-unused-components: error

theme:
    openapi:
        requiredPropsFirst: true
        noAutoAuth: true
        hideDownloadButton: true
        onlyRequiredInSamples: true
        nativeScrollbars: true
        scrollYOffset: 68
        colors:
            primary:
                main: '#1f9ec8'
        expandDefaultResponse: true
        expandDefaultRequest: true
        expandResponses: all
        schemaExpansionLevel: 2
        jsonSampleExpandLevel: 2
