module.exports = {
    legal: [
        {
            type: 'link',
            label: 'Company details (Impressum)',
            href: '/legal',
        },
        {
            type: 'category',
            label: 'Terms and Conditions',
            collapsible: false,
            className: 'section-header',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'latest/terms',
                },
            ],
        },
        {
            type: 'category',
            label: 'Apify Policies',
            collapsible: false,
            className: 'section-header',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'latest/policies',
                },
            ],
        },
    ],
};
