module.exports = {
    legal: [
        {
            type: 'category',
            label: 'Apify Terms and Policies',
            collapsible: false,
            className: 'section-header',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'latest',
                },
            ],
        },
    ],
};
