module.exports = {
    getStarted: [{ type: 'autogenerated', dirName: 'get-started' }],
    actors: [{ type: 'autogenerated', dirName: 'actors' }],
    storage: [{ type: 'autogenerated', dirName: 'storage' }],
    proxy: [{ type: 'autogenerated', dirName: 'proxy' }],
    integrations: [{ type: 'autogenerated', dirName: 'integrations' }],
    // Explicit so the agent quickstart can sit in the hub while keeping its own sidebar and URL.
    agentTools: [
        'agent-tools/index',
        { type: 'ref', id: 'get-started/agent-onboarding', label: 'Quickstart' },
        'agent-tools/plugin',
        'agent-tools/mcp',
        'agent-tools/skills',
        'agent-tools/agentic-payments',
        'agent-tools/docs-for-agents',
    ],
    account: [{ type: 'autogenerated', dirName: 'account' }],
    security: [{ type: 'autogenerated', dirName: 'security' }],
};
