module.exports = {
    getStarted: [{ type: 'autogenerated', dirName: 'get-started' }],
    actors: [{ type: 'autogenerated', dirName: 'actors' }],
    integrations: [{ type: 'autogenerated', dirName: 'integrations' }],
    account: [{ type: 'autogenerated', dirName: 'account' }],
};
