module.exports = {
    getStarted: [
        {
            type: 'autogenerated',
            dirName: 'get-started',
        },
    ],
    actors: [
        {
            type: 'autogenerated',
            dirName: 'actors',
        },
    ],
    storage: [
        {
            type: 'autogenerated',
            dirName: 'storage',
        },
    ],
    proxy: [
        {
            type: 'autogenerated',
            dirName: 'proxy',
        },
    ],
    integrations: [
        {
            type: 'autogenerated',
            dirName: 'integrations',
        },
    ],
    account: [
        {
            type: 'autogenerated',
            dirName: 'account',
        },
    ],
    security: [
        {
            type: 'doc',
            id: 'security',
        },
    ],
};
