extends: substitution
message: "Use '%s' instead of '%s'."
ignorecase: true
level: warning
scope: text
swap:
    # Product name changes
    'apify dashboard': Apify Console
    'apify console': Apify Console
    'Apify console': Apify Console
    'apify store': Apify Store
    'Apify store': Apify Store

    # Capitalization fixes
    'apify freelancers': Apify freelancers
    'apify platform': Apify platform

    # Proxy variations (simplified)
    'apify proxy': Apify Proxy
    'the apify proxy': Apify Proxy

    # Common abbreviations
    circa: approx.
    'ca\.': circa
