extends: existence
message: "The word '%s' should always be capitalized when referring to Apify products."
ignorecase: false
level: error
scope: text
tokens:
  # Apify Actors (the product) - avoid matching in URLs, code, or other contexts
  - '(?<![\/\-#\w])actors(?![\/\}])(?!\.\w)'
  
  # Apify Actor (the product) - avoid matching in URLs, code, or other contexts
  - '(?<![\/\-#\.`\w])actor(?![\/\}\-\w])(?! =)(?!\.\w)'
  
  # Apify Console (the product)
  - '(?<![\/\-#\.`\w])console(?![\/\}\-\w])(?! =)(?!\.\w)'
  
  # Apify Proxy (the product)
  - '(?<![\/\-#\.`\w])proxy(?![\/\}\-\w])(?! =)(?!\.\w)'
nonword: false
