extends: existence
message: "The word '%s' should always be capitalized when referring to Apify products."
ignorecase: false
level: error
scope: text
tokens:
  # Apify Actors - avoid matching in URLs, code, or other contexts
  - '(?<![\/\-#\w])actors(?![\/\}])(?!\.\w)'
  
  # Apify Actor - avoid matching in URLs, code, or other contexts
  - '(?<![\/\-#\.`\w])actor(?![\/\}\-\w])(?! =)(?!\.\w)'
  
  # Apify Console
  - '(?<![\/\-#\.`\w])console(?![\/\}\-\w])(?! =)(?!\.\w)'
  
  # Apify Proxy
  - '(?<![\/\-#\.`\w])proxy(?![\/\}\-\w])(?! =)(?!\.\w)'
nonword: false
