extends: substitution
message: "Use '%s' instead of '%s'."
ignorecase: false
level: warning
swap:
  'javascript|Javascript|javaScript': JavaScript
  '(?<!-)python(?!-)': Python
  'typescript|Typescript|typescript': TypeScript
  'nodejs|Nodejs|node.js': Node.js
  'Github': GitHub
  'chatgpt|Chatgpt|chatGPT': ChatGPT
  'Mongodb|mongodb': MongoDB
  'Postgresql|postgresql|postgres': PostgreSQL
  'vscode|VSCode|VS code': VS Code
  'Wordpress|wordpress': WordPress
  'N8n|N8N': n8n
  'Langchain|langchain': LangChain
