get:
  tags:
    - Actor builds/Get OpenAPI specification
  summary: Get OpenAPI specification
  description: |
    Get the OpenAPI specification for a specific Actor build.
    Authentication is based on the build's unique ID. No authentication token is required.
    
    **Note**: You can also use the `/api/v2/act-openapi-specification-get` endpoint to get the OpenAPI specification for a build.
  operationId: actorBuild_openapiSpecification_get
  security:
    - apiKeyActorBuilds: []
    - httpBearerActorBuilds: []
  parameters:
    - name: buildId
      in: path
      description: ID of the build you want to get, found in the build's `Info` tab.
      required: true
      style: simple
      schema:
        type: string
        example: soSkq9ekdmfOslopH
  responses:
    '200':
      description: ''
      headers: {}
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/actor-builds/GetOpenApiResponse.yaml"
