get:
  tags:
    - Actor builds/Build OpenAPI specification
  summary: Get OpenAPI specification
  description: |

    > **You can also use a [similar endpoint](/api/v2/act-openapi-specification-get)**
    > from the `acts` namespace to retrieve the OpenAPI specification for a build.

    This endpoint does not require the authentication token. Instead, calls are authenticated using a hard-to-guess ID of the build.
  operationId: actorBuild_openapiSpecification_get
  security:
    - apiKeyActorBuilds: []
    - httpBearerActorBuilds: []
  parameters:
    - name: buildId
      in: path
      description: 'ID of the build you want to get, found in the build''s `Info` tab.'
      required: true
      style: simple
      schema:
        type: string
        example: soSkq9ekdmfOslopH
  responses:
    '200':
      description: ''
      headers: {}
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/actor-builds/GetOpenApiResponse.yaml"
