name: apiary.io

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   name: Use Node.js 22
                uses: actions/setup-node@v4
                with:
                    node-version: 22

            -   name: Install apiaryio
                run: sudo gem install apiaryio

            -   name: Upload API docs to Apiary.io
                run: ./tools/upload_to_apiary.sh
                env:
                    APIARY_API_KEY: ${{ secrets.APIARY_API_KEY }}
