name: Build and deploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@master
      - name: install apiary
        run: sudo gem install apiaryio
      - name: Install dependencies
        run: npm install
      - name: Lint Markdown
        run: npm run lint:md:fix
      - name: Lint code
        run: npm run lint:code:fix
      - name: Build documentation
        run: npm run build
      - name: Upload docs to AWS S3
        run: ./src/scripts/upload_to_s3.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Upload API docs to Apiary.io
        run: ./src/scripts/upload_to_apiary.sh
        env:
          APIARY_API_KEY: ${{ secrets.APIARY_API_KEY }}
