name: Close pull request
on:
  pull_request:
    types: [closed]

jobs:
  close:
    name: Close
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: remove branch specific artifacts from AWS S3
        run: ./src/scripts/remove_branch_artifacts_from_s3.sh ${{ steps.extract_branch.outputs.branch }}
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
