name: 'Deploy Cloudformation'

on:
  workflow_dispatch:

  push:
    paths:
    - 'deploy/cloudformation/**'

jobs:
  get_values:
    uses: apify/workflows/.github/workflows/get_values.yaml@v0.27.0

  deploy_cloudformation:
    needs:
      - get_values
    uses: apify/workflows/.github/workflows/deploy_cloudformation.yaml@v0.27.0
    secrets:
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      slackToken: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
    with:
      stackName: apify-docs-preview
      templateFile: deploy/cloudformation/s3.yaml
      cloudformationRoleArn: arn:aws:iam::031263542130:role/ApifyCloudFormationServiceRole
      s3Bucket: apify-cf-templates-store-organization
      capabilities: CAPABILITY_NAMED_IAM
      revision: ${{ needs.get_values.outputs.short_commit_sha }}
