name: docs

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        environment:
            name: github-pages
        permissions:
            contents: write
            pages: write
            id-token: write
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v5
            -   name: Use Node.js 22
                uses: actions/setup-node@v5
                with:
                    node-version: 22
                    cache: 'npm'
                    cache-dependency-path: 'package-lock.json'
                    always-auth: 'true'

            -   name: Enable corepack
                run: |
                    corepack enable

            -   name: Build docs
                run: |
                    npm ci --force
                    npm run build
                env:
                    APIFY_SIGNING_TOKEN: ${{ secrets.APIFY_SIGNING_TOKEN }}
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                    INTERCOM_APP_ID: ${{ secrets.INTERCOM_APP_ID }}
                    SEGMENT_TOKEN: ${{ secrets.SEGMENT_TOKEN }}

            -   name: Set up GitHub Pages
                uses: actions/configure-pages@v5

            -   name: Upload GitHub Pages artifact
                uses: actions/upload-pages-artifact@v4
                with:
                    path: ./build

            -   name: Deploy artifact to GitHub Pages
                uses: actions/deploy-pages@v4

            -   name: Invalidate CloudFront cache
                run: gh workflow run invalidate.yaml --repo apify/apify-docs-private
                env:
                    GITHUB_TOKEN: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}
