name: docs

on:
    push:
        branches:
            - master

jobs:
    build:
        environment:
            name: github-pages
        permissions:
            contents: write
            pages: write
            id-token: write
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: Use Node.js 16
                uses: actions/setup-node@v3
                with:
                    node-version: 16

            -   name: Build docs
                run: |
                    npm ci --force
                    npm run build

            -   name: Set up GitHub Pages
                uses: actions/configure-pages@v3

            -   name: Upload GitHub Pages artifact
                uses: actions/upload-pages-artifact@v1
                with:
                    path: ./build

            -   name: Deploy artifact to GitHub Pages
                uses: actions/deploy-pages@v1
