name: Docs PR Previews

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

concurrency:
  cancel-in-progress: false
  group: 'docs-pr-previews-${{ github.event.pull_request.number }}'

jobs:
  trigger-preview:
    if: github.event.action != 'closed'

    runs-on: ubuntu-22.04-arm64

    steps:
      - name: Trigger preview
        run: gh workflow run apify_docs_pr.yml --repo apify/apify-docs-private --field pr-number=${{ github.event.pull_request.number }} --field original-repo=${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}

  delete-preview:
    if: github.event.action == 'closed'

    runs-on: ubuntu-22.04-arm64

    steps:
      - name: Delete preview
        run: gh workflow run apify_docs_pr.yml --repo apify/apify-docs-private --field pr-number=${{ github.event.pull_request.number }} --field original-repo=${{ github.repository }} --field action=delete
        env:
          GH_TOKEN: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}
