name: Spell check

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    spell_check:
        name: Spell check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            - name: Check spelling with typos
              uses: crate-ci/typos@631208b7aac2daa8b707f55e7331f9112b0e062d # v1.44.0
