module.exports = {
    courses: [
        {
            type: 'category',
            label: 'Web scraping & Automation',
            collapsible: false,
            className: 'section-header',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'webscraping',
                },
            ],
        },
        {
            type: 'category',
            label: 'Apify Platform',
            collapsible: false,
            className: 'section-header',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'platform',
                },
            ],
        },
    ],
    tutorials: [
        {
            type: 'category',
            label: 'Tutorials',
            collapsible: false,
            className: 'section-header',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'tutorials',
                },
            ],
        },
    ],
    glossary: [
        {
            type: 'category',
            label: 'Glossary',
            collapsible: false,
            className: 'section-header',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'glossary',
                },
            ],
        },
    ],
};
